## Multi-dimensional numpy arrays

Numpy arrays are not limited to one-dimensional arrays like those we have previously seen. In fact, various applications requires 2D or 3D arrays. Imagine wanting to provide the information about the intensity of pixels in a 2D black and white imageflat image, for example (this could be necessary to feed it to a Deep Neural Network for Machine Learning to recognise what the image corresponds to). In this case, you will need a 2D array where each element `pixel[i,j]` corresponds to the intensity of the pixel at position (i,j). In 3D rather than for a flat image, this would require a 3D array instead. If you wanted to provide the same information in time, you could do that with a 4D array...and so on.

In these notes, we will have a look at the most common functions provided by the Numpy library for the manipulation of these arrays, trying to take a pragmatic approach based on examples. As usual, you will need to run the cell below to load the Numpy library, which will be required for the following part.

In [1]:
import numpy as np

### Declaring (instantiating) a multi-dimensional array

Last time, we have seen an array declaration of the form: 

```Python
myArray = np.array( [ sequence_Of_Numbers ] )
```

and we made it looked like arrays are just 1D (one-dimensional) strings of elements (1D in the sense that each element can be specified by a single index). However, numpy arrays are much more general and can contain arrays of multiple dimensions. In fact, numpy arrays can be declared with an **arbitrary number of dimensions**, the only limitation being that of the memory they require to store them (*think*: this memory grows exponentially with the dimensionality of the array!).  

The declaration of a multi-dimensional array can be done very similarly to what one does with 1D array. In fact, one can call the `np.zeros` or `np.ones` functions of Numpy, which we have previously used to declare 1D arrays filled with zeros or ones in the following way:

```Python
myArray = np.zeros( ( length_of_dimension1, length_of_dimension2, ... ) )
```

```Python
myArray = np.ones(  ( length_of_dimension1, length_of_dimension2, ... ) )
```

As usual, a few examples might be more illustrative. Look at the array printed below by running the following cells.

In [2]:
a = np.zeros( ( 3, 2 ) ) # Note the DOUBLE parentheses. It is NOT np.zeros(3,2)!
b = np.ones( ( 4, 3 ) ) 
c = np.array( [ [0,0], [0,0], [0,0] ], dtype = 'float' ) 
d = np.array( [ [1,1,1], [1,1,1], [1,1,1], [1,1,1] ], dtype = 'float' ) 
print( 'Array a {0}'.format(a) )
print( 'Array b {0}'.format(b) )
print( 'Array c {0}'.format(c) )
print( 'Array d {0}'.format(d) )

Array a [[0. 0.]
 [0. 0.]
 [0. 0.]]
Array b [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array c [[0. 0.]
 [0. 0.]
 [0. 0.]]
Array d [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


We can also input the array using another declaration previously seen for 1D arrays, where we convert a list into an array. However, this time we need to input a "list of lists" (where each of these lists must have the same number of elements). In this case, the main index of the list (that runs over its elements, i.e. the sublists) is the first index of the array, the second index (that runs over the elements inside a sublist) is the second index of the 
array and so on. It should be almost intuitive and probably easier to show using a couple of examples! Run the cells below and observe what happens.

In [3]:
l1 = [ [ 1,2,3 ], [ 4,5,6 ], [7,8,9] ]
l2 = [ [ 1,2,0 ], [ 24,21,100 ], [ 90,10,100 ] ]
print("a is:")
a = np.array( l1 )
print(a)
i = 1
j = 2
print("Element a[{0},{1}] is: {2}".format( i, j, a[ i, j ] ) )

print("b is:")
b = np.array( l2 )
print(b)
i = 0
j = 0
print("Element b[{0},{1}] is: {2}".format( i, j, b[ i, j ] ) )

a is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element a[1,2] is: 6
b is:
[[  1   2   0]
 [ 24  21 100]
 [ 90  10 100]]
Element b[0,0] is: 1


### Retrieving values and slicing

If you want to retrieve the value of the element at position (i,j,..,..,z) in the array (again, one index for each dimension!), you can do it similarly to what you would do for a list, with two equivalent declarations, either:

```Python
value = arrayName[ i, j ]
```

or

```Python
value = arrayName[ i ][ j ]
```

Read and run this cell to convince yourself!

In [4]:
l1 = [ [ 1,2,3 ], [ 4,5,6 ], [7,8,9] ]
print("a is:")
a = np.array( l1 )
print(a)
i = 1
j = 2
methodOne = a[ i, j ]
methodTwo = a[ i ][ j ]
print("Element a[{0},{1}] is: {2}".format( i, j, methodOne ) )
print("Element a[{0}][{1}] is: {2}".format( i, j, methodTwo ) )

a is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element a[1,2] is: 6
Element a[1][2] is: 6


Also in the same way that you do with lists, you can call an entire row or column (or a part of an array if you are more than in 2D!). If `myArray` is a 2D array, then `myArray[i]` (or, equivalently, `myArray[i][:]` or `myArray[i,:]` is the i-th row in the array. 

Similarly, but not exactly in the same way `myArray[:,i]` is the i-th column. However, in this case you cannot use the declaration `myArray[:][i]`. This latter declaration in Python turns out to be equivalent to `myArray[i]` (or `myArray[i][:]`) rather than `myArray[:, i]`. The reason, in all honesty, is because of a somewhat arbitrary choice of the developers of numpy.

Another important thing to notice is that, **with the rightmost index only** (so the index `j` in `a[i,j]`, or the index `k` in `a[i,j,k]`, and so on), you can use slicing techniques, exactly as you used in lists. This is more easily shown than explained it in writing in an abstract way. You can play around by changing and running the next three cells to see a few examples. Change the indices and see what is printed out (but first, always think about what you would expect and write it down for comparison)!

In [5]:
l1 = [ [ 1,2,3 ], [ 4,5,6 ], [7,8,9] ]
print("a is:")
a = np.array( l1 )
print(a)
i = 1
j = 2
firstRow1 = a[ 0, : ]
firstRow2 = a[ 0 ][ : ]
firstRow3 = a[ 0 ]
print("The first row is of a, using a[ 0, : ], is: {0}".format( firstRow1 ) )
print("The first row is of a, using a[ 0 ][ : ], is: {0}".format( firstRow2 ) )
print("The first row is of a, using a[ 0 ], is: {0}".format( firstRow3 ) )

a is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The first row is of a, using a[ 0, : ], is: [1 2 3]
The first row is of a, using a[ 0 ][ : ], is: [1 2 3]
The first row is of a, using a[ 0 ], is: [1 2 3]


In [6]:
# Example 2 with columns
l1 = [ [ "a", "b", "c" ], [ "d", "e", "f" ], [ "h", "i", "j" ] ]
print("a is:")
a = np.array( l1 )
print(a)
i = 1
j = 2
firstC1 = a[ :, 0 ]
firstC2 = a[ : ][ 0 ]
print("The first column of a, using a[ :, 0 ], is: {0}".format( firstC1 ) )
print("BUT a[ : ][ 0 ], is: {0}".format( firstC2 ) )

a is:
[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['h' 'i' 'j']]
The first column of a, using a[ :, 0 ], is: ['a' 'd' 'h']
BUT a[ : ][ 0 ], is: ['a' 'b' 'c']


In [7]:
# Example 2 splicing of last index
l1 = [ [ "a", "b", "c" ], [ "d", "e", "f" ], [ "h", "i", "j" ], [ "k", "l", "m" ] ]
print("a is:")
a = np.array( l1 )
print(a)
i = 1
j = 2
splice1 = a[ 0 ][ 1: ]
splice2 = a[ 1 ][ :-1 ]
print("Taking only elements of the first row (row 0), excluding the first, using a[ 0, 1: ]:" )
print("{0}".format( splice1 ) )

print("Taking only elements of the second row (row 1), excluding the last, using a[ 1, :-1 ]:" )
print("{0}".format( splice2 ) )

a is:
[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['h' 'i' 'j']
 ['k' 'l' 'm']]
Taking only elements of the first row (row 0), excluding the first, using a[ 0, 1: ]:
['b' 'c']
Taking only elements of the second row (row 1), excluding the last, using a[ 1, :-1 ]:
['d' 'e']


**Quick note:** Probably without noticing it, we have previously used 2D arrays when importing data using the `np.loadtxt( "nameOfFile")` function. The data is interpreted as a 2-Dimensional array where N, the length of the first dimension, is the number of rows in the datafile and the second index runs over all columns
in it.

### An example of a 3D array:

Although we are going to use numpy array primarily as 1 and 2-dimensional arrays, there is actually
**no limit to it**, we can use an arbitrary number of dimensions (if space in memory allows). Run the example here to see how a 3D array looks like. Change the values to see a few different realisations.

In [8]:
b = np.ones( (4,4,2) ) 
b[0,1,1] = "4.0"
b[1,2,1] = "5.0"
b[2,2,1] = "6.0"
print(b)

[[[1. 1.]
  [1. 4.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 5.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 6.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### Useful data and method attributes of a numpy array

Properties of arrays can be read using their data attributes. For example, `shape` is the shape of the array, or in other words it returns the size of each dimension. Run this cell to check what happens:

In [9]:
b = np.array( [ [1,2,3],[4,5,6] ]) 
print( b.shape )

(2, 3)


Check into the documentation, either [online](https://numpy.org/doc/stable/) on the numpy manual or printing the related documentation directly from Jupyter, what is the meaning of the attributes in the next cells.  
Write a few examples by yourself by instantiating an array and run to see what happens. Take note of whether they are data attributes or they are method attributes (values or functions of the class ndarray).  

**Helpful reminder**: when you see in the documentation a function described as: `functionName( i [, j, k, ... ] )` it means that `i` is a required input whereas `j,k,...` are optional ones (what we called keyword arguments, which have been provided a default value in their definition).

In [13]:
# Attribute 1: ".T"
print(b.T)


[[1 4]
 [2 5]
 [3 6]]


In [15]:
# Attribute 2: ".ravel()"
print(b.ravel())
print("")
print(help(b.ravel))


[1 2 3 4 5 6]

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.

None


Try to answer this question: What is the difference between `.reshape()` and `.resize()`? 
Check in the numpy documentation online and build an example below!

In [19]:
print(help(b.reshape))
print("")
print(help(b.resize))

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.

None

Help on built-in function resize:

resize(...) method of numpy.ndarray instance
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    

In [ ]:
# Attribute 3: ".reshape( dim1 [, dim2 ] )" 


In [ ]:
# Attribute 4: ".resize( dim1 [, dim2 ] )" 


In [ ]:
# Attribute 5 and 6: the ".all()" and ".any()" attribute...for multi-dimensional arrays
# Check what are the default values for the optional ("keyword", in python jargon) arguments



In [ ]:
# the ".mean()" and "".std()" attributes. You have seen this for 1D arrays, but for 2D they can
# do a lot more. Check the value / meaning of the optional arguments by looking at the documentation!
# Write some examples and check what happens to see if you have understood!



### Merging arrays

Here we will now have a look at a couple of Numpy functions to combine arrays together. More precisely, we will look at ways in which we can take 2 (or more) arrays of the same dimensionality to generate one with the same dimensionality of the starting ones but a different (larger) number of elements (which is why we say we merge the arrays).

To do that, we can use the `np.vstack( (array1, array2) )` ( "vertically stack") and the 
`np.hstack( (array1, array2) )` ("horizontally stack") functions. In two dimensions it is easy to visualise what they do: if you have two 2D arryas, `vstack` creates a third `2D` array stacking them one on top of each other (from bottom to top), whereas `hstack` merge them putting them one next two each other (from left to right). So, for example, if you `vstack` two 2D arrays each with `NxM` entries (where `N` and `M` are the maximum value taken by the first and second index of the array), the element `a[i,j]` becomes the element `a[i + N,j]` in the merged array, whereas if you `hstack` them the element `a[i,j]` becomes the element `a[i,j+M]` in the resulting array. 

**Quick note:** both `vstack` and `hstack` take as an input a tuple of `N` arrays to be stacked, not just 2.   

Run the examples below to see what happens!    

In [ ]:
a = np.zeros(( 2,4 ))
b = np.ones((2,4))

print( "a is:")
print( a)
print( "b is:")
print( b)

c = np.vstack( (a,b) )
print("a and b stack vertically is")
print(c)
d = np.hstack( (a,b) )
print("a and b stack horizontally gives")
print(d)
e = np.hstack( (a,b,a,b) )
print("Or stacking multiple arrays, like (a,b,a,b) stack horizontally ")
print(e)


In [ ]:
# Write some code here to experiment stacking different arrays together



### Splitting arrays

"Splitting" arrays is the opposite of stacking them. Run the next cell (and change
inputs to experiment with it!) to see some examples and check the relative 
documentation online if still unclear, but if you understood how `vstack` and `hstack` works, their opposite operation `vsplit` and `hsplit` should be quite clear!

In [ ]:
np.hsplit(a,3)
np.vsplit(a,3)


a = np.ones(6)
b = np.split(a,2 )
c = np.split(a,3 )

print( a)
print( b )
print( c )

In [ ]:
# Write some code here to experiment stacking different arrays together



### Applying functions to N-dimensional arrays

When applying functions to multi-dimensional arrays, exactly as for 1D array Python assumes that properties are applied *elementwise*. This is also valid when combining two arrays using arithmetic operations such as +, -, * or /. 

**Be extremely careful**. Because operations are applied elementwise, you should **not confuse 2D numpy arrays with 2D 
matrices** (if you do not know what yet what matrices are, you will see it in the math course later in the year). For example, the product between two arrays is completely different from the product between two matrices (but sum and subtractions are instead the same).  

If you want to force Python to interpret your 2D array as if it was a matrix, Numpy allows you to do that. In fact, there are a lot of functionalities to do linear algebra in Numpy (and its related package, Scipy). However, we will not see them here, at least not this year!

As usual, have a look at the following examples to see what happens when operations are applied to multi-dimensional arrays.

In [ ]:
a = np.array( [ [1,2],[3,4] ] )
b = np.array( [ [1,1],[2,2] ] )

c = a * b
print("a is")
print(a)
print("b is")
print(b)
print("Their product is elementwise, so c = a * b gives")
print(c)